# Robot MCP System Configuration
system:
  name: "Robot Guidance System"
  version: "1.0.0"
  log_level: "INFO"
  context_update_interval: 60  # seconds
  telemetry_retention_hours: 24
  chat_history_limit: 20

database:
  postgres:
    host: "localhost"
    port: 5432
    database: "rag_db"
    username: "postgres"
    password: "password"
    pool_size:
      min: 1
      max: 10
  
  qdrant:
    host: "localhost"
    port: 6333
    collection_name: "robot_telemetry"

llm:
  model_name: "llama3.3:70b-instruct-q5_K_M"
  embedding_model: "all-MiniLM-L6-v2"
  vector_dimension: 384
  max_retries: 2
  timeout_seconds: 30

robot:
  waypoints:
    - reception
    - cafeteria
    - meeting_room_a
    - meeting_room_b
    - elevator
    - exit
    - main_hall
  
  navigation:
    max_waypoints_per_command: 5
    timeout_seconds: 300
    stuck_detection_threshold: 60

server:
  host: "127.0.0.1"
  port: 5000
  cors_origins: ["*"]
  max_concurrent_requests: 100